### ISSUE TITLE
go1.16.5 linux/amd64 编译报错

### ISSUE THREAD

**Issue by fishg** [Kr328/tun2socket-lwip#1]
go build
# github.com/kr328/tun2socket
/home/fishg/go/pkg/mod/github.com/!kr328/tun2socket-lwip@v0.0.0-20210620052129-ba5ce167b596/link.go:46:13: could not determine kind of name for C.link_attach
/home/fishg/go/pkg/mod/github.com/!kr328/tun2socket-lwip@v0.0.0-20210620052129-ba5ce167b596/link.go:40:2: could not determine kind of name for C.link_close
/home/fishg/go/pkg/mod/github.com/!kr328/tun2socket-lwip@v0.0.0-20210620052129-ba5ce167b596/link.go:59:2: could not determine kind of name for C.link_free
/home/fishg/go/pkg/mod/github.com/!kr328/tun2socket-lwip@v0.0.0-20210620052129-ba5ce167b596/link.go:22:7: could not determine kind of name for C.link_read
/home/fishg/go/pkg/mod/github.com/!kr328/tun2socket-lwip@v0.0.0-20210620052129-ba5ce167b596/link.go:18:11: could not determine kind of name for C.link_t
/home/fishg/go/pkg/mod/github.com/!kr328/tun2socket-lwip@v0.0.0-20210620052129-ba5ce167b596/link.go:31:7: could not determine kind of name for C.link_write

**Comment by Kr328** [comment]
需要 go generate

**Comment by fishg** [comment]
> 需要 go generate
当作clash的模块，不知道怎么才能编译了，windows x86_64，分支：https://github.com/yaling888/clash/tree/with-tun

**Comment by Kr328** [comment]
这就要考验你自己的 Go 基础了

这个库的工作不包括帮你处理这些杂活
